services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    # environment:
    #   - SECRET_key=test
    #   - DEBUG=True
    #   or any other dynamic variable!

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'   # web interface
      - '25:25'     # SMTP server
      - '143:143'   # IMAP server
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"  # Locust web UI
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
    depends_on:
      - backend

  worker:
    image: locustio/locust
    container_name: locust-worker
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    depends_on:
      - master


volumes:
  smtp4dev-data:
