services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    # environment:
    #   - SECRET_key=test
    #   - DEBUG=True
    #   or any other dynamic variable!
